disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - function_body_length
 - line_length
excluded: # paths to ignore during listing. Takes precedence over `included`.
  - Pods
